rvm: 1.9.3

language: objective-c

before_script:
   - pod --version
   - gem which cocoapods
   - gem update cocoapods --no-ri --no-rdoc
   - sudo easy_install cpp-coveralls

script:
   - cd Project/PrYv-OSX-Example/
   - pod install
   - xcodebuild test -workspace PrYv-OSX-Example.xcworkspace -scheme PrYv-OSX-Example -verbose -configuration Coverage

after_success:
   - echo `pwd`
   - find `pwd`/Library/Developer/Xcode/DerivedData/ | grep gcda
   - ruby ../../coveralls.rb --extension m --exclude-folder PrYv-OSX-Example/
