rvm: 1.9.3
language: objective-c
before_install: cd Project/PrYv-OSX-Example
script:
  - xcodebuild -workspace PrYv-OSX-Example.xcworkspace -scheme PrYv-OSX-Example -verbose -configuration Debug
  - xcodebuild test -workspace PrYv-OSX-Example.xcworkspace -scheme PrYv-OSX-Example -verbose -configuration Debug